import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbconfig";
// import MainProvider from "./component/MainProvider";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "300", style: "normal", subsets: ["latin"]  });

export const metadata: Metadata = {
  title: "Product Information",
  description: "Generated by Product Information",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body className={poppins.className}> {children}
        {/* <MainProvider> */}
          {/* <div className="text-blue-950"></div> */}
        {/* </MainProvider> */}
      </body>
    </html>
  );
}